services:
  db:
    image: postgres:15
    container_name: chatbot_postgres
    restart: always
    environment:
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_pass
      POSTGRES_DB: chatbot_db
    ports:
      - "5433:5432"
    volumes:
      - ./db/chatbot_schema.sql:/docker-entrypoint-initdb.d/chatbot_schema.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

